#!/bin/bash
set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

export N_PREFIX="${BUILDKITE_PLUGIN_NODE_N_TOOL_INSTALL_DIR:-$HOME/n}"

[[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"

if ! n --version >/dev/null 2>&1 ; then
  echo "--- installing N tool in ${N_PREFIX}"
  curl -s -L https://git.io/n-install | bash -s -- -y -;
fi

NODE_VERSION="${BUILDKITE_PLUGIN_NODE_N_NODE_VERSION:-lts}"

echo "~~~ :nodejs: installing node version ${NODE_VERSION}"
n install "${NODE_VERSION}"

export PATH
